kind: Deployment
apiVersion: apps/v1
metadata:
  name: azdeploy
  namespace: azdeploy
  labels:
    app: azdeploy
    name: azdeploy

spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdeploy
      task: azdeploy
  template:
    metadata:
      labels:
        app: azdeploy
        task: azdeploy
    spec:
      containers:
        - name: azdeploy
          image: lawisnie/azdeploy:1018
          env:
            - name: AZPAT
              valueFrom:
                secretKeyRef:
                  name: azdeploy-pat
                  key: value
          resources:
            limits:
              cpu: '0.25'
              memory: 1024Mi
