name: azdeploy-$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  paths:
    include:
      - azdeploy/*

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildDocker
    steps:
    - task: Docker@2
      displayName: Docker Login
      inputs:
        containerRegistry: 'DockerHub'
        command: 'login'
        addPipelineData: false
        addBaseImageData: false
    - script: cd azdeploy && ./build.sh lawisnie/azdeploy $(Build.BuildId)
      displayName: Build & Push Image