version: "3"
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    networks:
      - db
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=lawisnie@figtreesoftware.com
      - PGADMIN_DEFAULT_PASSWORD=foo
networks:
  db:
    external:
      name: db