version: '3'
services:
  vsts_agent:
    image: dockeragent:latest # Has "standard" vsts tools, as well as docker and cypress.io support.  See https://hub.docker.com/r/microsoft/vsts-agent/
    ipc: host # Needed for cypress docker issue: https://github.com/cypress-io/cypress/issues/350
    restart: always
    environment:
      - VSTS_ACCOUNT=figtreesoftware
      - VSTS_TOKEN_FILE=/var/vsts/vsts_credentials
      - VSTS_AGENT=Default
      - VSTS_WORK=/var/vsts/work
      - VSTS_POOL=WIKICYPRESS
    volumes:
      - ~/vsts:/var/vsts
      - ~/.vsts/credentials:/var/vsts/vsts_credentials
      - /var/run/docker.sock:/var/run/docker.sock