kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx
  namespace: nginx
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  tls:
    - hosts:
        - 'wikideb.home'
      secretName: wikideb-home-tls
  rules:
    - host: figtreesoftware.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
    - host: wikideb.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
