apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: figtreesoftware-com
  namespace: default
spec:
  secretName: figtreesoftware-com-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: figtreesoftware.com
  dnsNames:
    - figtreesoftware.com
