version: '3.2'
services:

    site-a:
        restart: always
        image: nginx
        networks:
            - proxy
            - db
        environment:
            - VIRTUAL_HOST=dev1.figtreesoftware.com
            - LETSENCRYPT_HOST=dev1.figtreesoftware.com
            - LETSENCRYPT_EMAIL=admin@figtreesoftware.com

    site-b:
        restart: always
        image: httpd
        networks:
            - proxy
            - db
        environment:
            - VIRTUAL_HOST=dev2.figtreesoftware.com
            - LETSENCRYPT_HOST=dev2.figtreesoftware.com
            - LETSENCRYPT_EMAIL=admin@figtreesoftware.com

    webjobs:
        restart: always
        image: lawisnie/default:webjobs-latest
        networks:
            - proxy
            - db
        environment:
            - VIRTUAL_HOST=webjobs.figtreesoftware.com
            - LETSENCRYPT_HOST=webjobs.figtreesoftware.com
            - LETSENCRYPT_EMAIL=admin@figtreesoftware.com

    # Database
    mongo:
        image: mongo:3.6-jessie
        restart: always
        networks:
            - db
        volumes:
            - $HOME/mongo/data/db:/data/db
        ports:
            - 27017:27017

    # NGINX reverse proxy so that we can host multiple sites under the same domain, on the same machine!
    proxy:
        restart: always
        image: jwilder/nginx-proxy
        networks:
            - proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - $HOME/certs:/etc/nginx/certs:ro
            - $HOME/nginx/vhost.d:/etc/nginx/vhost.d
            - $HOME/nginx/html:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

    # This container is a companion to nginx-proxy that retrieves and configures ssl certificates from Let'sEncrypt
    proxy-ssl:
        restart: always
        image: jrcs/letsencrypt-nginx-proxy-companion
        networks:
            - proxy
        volumes:
            - $HOME/certs:/etc/nginx/certs:rw
            - $HOME/nginx/vhost.d:/etc/nginx/vhost.d
            - $HOME/nginx/html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
    proxy:
        external:
            name: figtreeproxy
    db:
        driver: bridge
