name: azbuild-$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  paths:
    include:
      - azbuild/*

parameters:
  - name: Image
    displayName: Agent Pool
    type: string
    default: Pittsburgh
    values:
      - Pittsburgh
      - ubuntu-latest
      - macOS-latest

pool:
${{ if eq(parameters['Image'], 'Pittsburgh') }}:
  name: Pittsburgh
${{ if ne(parameters['Image'], 'Pittsburgh') }}:
  vmImage: ${{parameters['Image']}}


stages:
- stage: Build
  jobs:
  - job: BuildDocker
    steps:
    - task: Docker@2
      displayName: Docker Login
      inputs:
        containerRegistry: 'DockerHub'
        command: 'login'
        addPipelineData: false
        addBaseImageData: false

    - script: cd azbuild && ./build.sh lawisnie/azbuild $(Build.BuildNumber)
      displayName: Build & Push Image
      #failOnStderr: true