name: azbuild-$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  paths:
    include:
      - azbuild/*

parameters:
  - name: agent
    displayName: Agent Pool
    type: string
    default: Pittsburgh
    values:
      - Pittsburgh
      - ubuntu-latest
      - macOS-latest

variables:
  selfhostedagent: Pittsburgh

stages:
- stage: Build
  jobs:
    - job: selfhostedagent
      condition: eq(${{ parameters.agent }}, $(selfhostedagent))
      displayName: Build Docker
      pool:
        name: Pittsburgh
        # demands:
        #   - Agent.Name -equals WS-VITOL-01
      steps:
        - template: ../templates/build-docker.yml
          parameters:
            name: azbuild

    - job: hostedagent
      condition: ne(${{ parameters.agent }}, $(selfhostedagent))
      displayName: Build Docker
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: ../templates/build-docker.yml
          parameters:
            name: azbuild
    