version: '3'
services:
  vsts_agent:
    image: microsoft/vsts-agent:ubuntu-16.04-docker-18.06.1-ce-standard # Has "standard" vsts tools, as well as docker support.  See https://hub.docker.com/r/microsoft/vsts-agent/
    restart: always
    environment:
      - VSTS_ACCOUNT=figtreesoftware
      - VSTS_TOKEN_FILE=/var/vsts/vsts_credentials
      - VSTS_AGENT=WIKIDOCKER
      - VSTS_WORK=/var/vsts/work
      - VSTS_POOL=Pittsburgh
    volumes:
      - /var/vsts:/var/vsts
      - ~/.vsts/credentials:/var/vsts/vsts_credentials
      - /var/run/docker.sock:/var/run/docker.sock