# Taken from https://github.com/SeleniumHQ/docker-selenium
# 06/01/2018
# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.12.0-boron
    restart: always
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=10
  chrome:
    image: selenium/node-chrome:3.12.0-boron
    restart: always
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION=10
      - NODE_MAX_INSTANCES=10
  # firefox:
  #   image: selenium/node-firefox:3.12.0-boron
  #   restart: always
  #   depends_on:
  #     - selenium-hub
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444